import {Dimensions} from 'react-native';

// Declaring constants
export const DOSIS_BOLD = 'Dosis-Bold';
export const DOSIS_MEDIUM = 'Dosis-Medium';
export const DOSIS_REGULAR = 'Dosis-Regular';
export const DOSIS_SEMIBOLD = 'Dosis-SemiBold';
export const FONT_SIZE_XXS = 10;
export const FONT_SIZE_XS = 12;
export const FONT_SIZE_SM = 14;
export const FONT_SIZE_MD = 16;
export const FONT_SIZE_LG = 20;
export const FONT_SIZE_XL = 24;

export const SCREEN_WIDTH = Dimensions.get('window').width;
export const SCREEN_HEIGHT = Dimensions.get('window').height;
export const STANDARD_LOGO_WIDTH = 177.5;
export const STANDARD_LOGO_HEIGHT = 217.5;
export const STANDARD_COUPON_HEIGHT = 200;
export const STANDARD_FLEX = 1;
export const STANDARD_Z_INDEX = 1;
export const STANDARD_SPACING = 5;
export const STANDARD_CHECKBOX_SIZE = 30;
export const STANDARD_BORDER_RADIUS = 5;
export const STANDARD_BORDER_WIDTH = 1;
export const STANDARD_BADGE_PILL_WIDTH = 75;
export const STANDARD_BUTTON_HEIGHT = 45;
export const STANDARD_NAVIGATION_LINK_HEIGHT = 50;
export const STANDARD_NAVIGATION_LINK_LEFT_ICON_WRAPPER_SIZE = 35;
export const STANDARD_TEXT_INPUT_HEIGHT = 45;
export const STANDARD_TEXTAREA_HEIGHT = 90;
export const STANDARD_SELECT_DROPDOWN_HEIGHT = 45;
export const STANDARD_VECTOR_ICON_WRAPPER_SIZE = 35;
export const STANDARD_VECTOR_ICON_SIZE = 20;
export const STANDARD_USER_AVATAR_WRAPPER_SIZE = 40;
export const STANDARD_USER_AVATAR_BADGE_WRAPPER_SIZE = 15;
export const STANDARD_SOCIAL_ICON_SIZE = 40;
export const STANDARD_LANGUAGE_RADIO_WRAPPER_HEIGHT = 60;
export const STANDARD_LANGUAGE_RADIO_CHECKBOX_SIZE = 15;
export const STANDARD_PRODUCT_CARD_SIZE = 110;
export const STANDARD_PRODUCT_IMAGE_WRAPPER_SIZE = 75;
export const STANDARD_DIVIDER_LINE_HEIGHT = 1;
export const STANDARD_LANGUAGE_CARD_HEIGHT = 60;
export const STANDARD_LANGUAGE_FLAG_SIZE = 30;
export const STANDARD_PAYMENT_METHOD_CARD_HEIGHT = 60;
export const STANDARD_LOTTIE_FILE_SIZE = 125;
export const STANDARD_OTP_TEXT_VIEW_SIZE = 40;
export const STANDARD_OTP_TEXT_VIEW_BORDER_SIZE = 1;
export const STANDARD_BRAND_LOGO_WRAPPER_SIZE = 55;
export const STANDARD_ON_BOARDING_IMAGE_SIZE = 250;
export const STANDARD_ON_BOARDING_PAGINATION_DOT_HEIGHT = 6;
export const STANDARD_WALLET_CARD_HEIGHT = 175;
export const STANDARD_WALLET_BILL_AND_RECHARGE_ICON_SIZE = 60;
export const STANDARD_WALLET_TRANSACTION_DATE_SIZE = 40;
export const STANDARD_DRAWER_WIDTH = 260;
export const STANDARD_DRAWER_HEADER_HEIGHT = 140;

